steps:
  # Step 1: Cài Python packages cho Composer từ requirements.txt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'update-composer-packages'
    entrypoint: gcloud
    args:
      - composer
      - environments
      - update
      - ${_COMPOSER_ENVIRONMENT}
      - --location=${_COMPOSER_LOCATION}
      - --update-pypi-packages-from-file=requirements.txt

  # Step 2: Upload DAGs lên Composer bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'upload-dags'
    entrypoint: bash
    args:
      - -c
      - |
        python -m pip install --user google-cloud-storage==2.19.0 && \
        python deploy_to_composer.py \
          --dags_directory=${_DAGS_DIRECTORY} \
          --composer_bucket=${_COMPOSER_BUCKET}

  # Step 3: Upload plugins lên Composer bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'upload-plugins'
    entrypoint: bash
    args:
      - -c
      - |
        python -m pip install --user google-cloud-storage==2.19.0 && \
        python deploy_to_composer.py \
          --plugins_directory=${_PLUGINS_DIRECTORY} \
          --composer_bucket=${_COMPOSER_BUCKET}

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'SECRET_MANAGER_PROJECT_ID=${PROJECT_ID}'

substitutions:
  _DAGS_DIRECTORY: "dags/"
  _PLUGINS_DIRECTORY: "plugins/"
  _COMPOSER_BUCKET: "asia-southeast1-adventure-works-landing"
  _COMPOSER_ENVIRONMENT: "vunewbie-adventure-works"
  _COMPOSER_LOCATION: "asia-southeast1"
