steps:
  # Step 1: Install Python dependencies for deployment script(first time only)
  # - name: 'python'
  #   entrypoint: pip
  #   args: ["install", "-r", "requirements.txt", "--user"]
  #   id: 'install-deps'

  # Step 2: Upload DAGs to Composer bucket
  - name: 'python'
    entrypoint: python
    args:
      - "deploy_to_composer.py"
      - "--dags_directory=${_DAGS_DIRECTORY}"
      - "--composer_bucket=${_COMPOSER_BUCKET}"
    id: 'upload-dags'
    waitFor: ['install-deps']

  # Step 3: Upload plugins to Composer bucket
  - name: 'python'
    entrypoint: python
    args:
      - "deploy_to_composer.py"
      - "--plugins_directory=${_PLUGINS_DIRECTORY}"
      - "--composer_bucket=${_COMPOSER_BUCKET}"
    id: 'upload-plugins'
    waitFor: ['upload-dags']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'SECRET_MANAGER_PROJECT_ID=${PROJECT_ID}'

substitutions:
  _DAGS_DIRECTORY: "dags/"
  _PLUGINS_DIRECTORY: "plugins/"
  _COMPOSER_BUCKET: "asia-southeast1-adventure-works-landing"
